flaskr/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from flaskr.forms import SignupForm, LoginForm, PostForm, SearchPostForm, CommentForm
from flaskr.models import User, Post, Comment, PostLike
from flask_login import login_user, logout_user, login_required, current_user
import datetime
from flaskr import db


bp = Blueprint('app', __name__, url_prefix='')

@bp.route('/')
@bp.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=15)
    trend_posts = Post.query.order_by(Post.like_count.desc()).limit(6)
    return render_template('home.html', posts=posts, trend_posts=trend_posts)

@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        user = User(
          username,
          email,
          password
        )
        user.add_user()
        return redirect(url_for('app.login'))
    return render_template('signup.html', form=form)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        email = form.email.data
        password = form.password.data
        user = User.select_user_by_email(email)
        if user and user.validate_password(password):
            login_user(user)
            next = request.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
    return render_template('login.html', form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('app.home'))

@bp.route('/post', methods=['GET','POST'])
@login_required
def post():
    form = PostForm(request.form)
    if request.method == 'POST' and form.validate():
        author = form.author.data
        date_posted = datetime.datetime.now()
        content = form.content.data
        user_id = form.user_id.data
        like_count = 0
        post = Post(
            author,
            date_posted,
            content,
            user_id,
            like_count
        )
        post.add_post()
        return redirect(url_for('app.home'))
    return render_template('post.html', form=form)

@bp.route('/user_profile/<int:user_id>')
def user_profile(user_id):
    user = User.query.filter(User.id==user_id).first()
    # posts = Post.query.filter(Post.user_id==user_id).all()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter(Post.user_id==user_id).order_by(Post.date_posted.desc()).paginate(page=page, per_page=15)
    return render_template('user_profile.html', user=user, posts=posts)

@bp.route('/post_detail/<int:post_id>')
def post_detail(post_id):
    post = Post.query.filter(Post.id==post_id).first()
    comments = Comment.query.filter(Comment.comment_id==post_id).all()
    return render_template('post_detail.html', post=post, comments=comments)

@bp.route('/likes/<int:post_id>/<action>')
@login_required
def likes(post_id, action):
    post = Post.query.filter(Post.id==post_id).first()
    if action == 'like':
        current_user.like_post(post)
        post.like_count += 1
        db.session.commit()
    elif action == 'unlike':
        current_user.unlike_post(post)
        post.like_count -= 1
        db.session.commit()
    return redirect(url_for('app.post_detail', post_id=post_id))

@bp.route('/delete_post/<int:post_id>')
@login_required
def delete_post(post_id):
    post = Post.query.filter(Post.id==post_id).first()
    post.delete_post()
    return redirect(url_for('app.home'))

@bp.route('/search_posts', methods=['GET', 'POST'])
def search_posts():
    form = SearchPostForm(request.form)
    posts = None
    if request.method == 'POST' and form.validate():
        posts_contents = form.posts_contents.data
        posts = Post.search_by_contents(posts_contents)
    return render_template('search_posts.html', form=form, posts=posts)

@bp.route('/comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def comment(post_id):
    form = CommentForm(request.form)
    if request.method == 'POST' and form.validate():
        author = form.author.data
        content = form.content.data
        date_posted = datetime.datetime.now()
        comment_id = form.comment_id.data
        comment = Comment(
            author,
            content,
            date_posted,
            comment_id
        )
        comment.add_comment()
        return redirect(url_for('app.post_detail', post_id=post_id))
    return render_template('comment.html', form=form, post_id=post_id)

@bp.route('/comment_delete/<int:post_id>/<int:comment_id>')
@login_required
def comment_delete(post_id, comment_id):
    comment = Comment.query.filter(Comment.id==comment_id).first()
    comment.delete_comment()
    post = Post.query.filter(Post.id==post_id).first()
    post_id = post.id
    return redirect(url_for('app.post_detail', post_id=post_id))

@bp.route('/liked_posts/<int:user_id>')
@login_required
def liked_posts(user_id):
    post_likes = PostLike.query.filter(PostLike.user_id==user_id).all()
    liked_posts = []
    page = request.args.get('page', 1, type=int)
    for post_like in post_likes:
        liked_post = Post.query.filter(Post.id==post_like.post_id).first()
        liked_posts.append(liked_post)
    return render_template('liked_posts.html', liked_posts=liked_posts)

flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>Twitter</title>

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <style>
    #wrapper {
      overflow-x: hidden;
   }
  
  #sidebar-wrapper {
    position: fixed;
    left: 0px;
    top: 0px;
    min-height: 100vh;
    margin-left: -15rem;
    -webkit-transition: margin .25s ease-out;
    -moz-transition: margin .25s ease-out;
    -o-transition: margin .25s ease-out;
    transition: margin .25s ease-out;
  }

  #content-header {
    width: 100%;
    position: fixed;
    top: 0px;
    left: 16%;
    z-index: 1;
  }

  #post-content-area {
    width: 64%;
    margin: 5% auto;
  }


  #sidebar-wrapper .sidebar-heading {
    padding: 0.875rem 1.25rem;
    font-size: 1.2rem;
  }
  
  #sidebar-wrapper .list-group {
    width: 15rem;
  }
  
  #page-content-wrapper {
    min-width: 100vw;
  }
  
  #wrapper.toggled #sidebar-wrapper {
    margin-left: 0;
  }
  
  @media (min-width: 768px) {
    #sidebar-wrapper {
      margin-left: 0;
      width: 26%;
      z-index: 2;
    }
  
    #page-content-wrapper {
      min-width: 0;
      width: 100%;
    }
    #wrapper.toggled #sidebar-wrapper {
      margin-left: -15rem;
    }
  }

  #trend-area{
    position: fixed;
    top: 0px;
    right: 0%;
    width: 26%;
    height: 100%;
    background-color: #f8f9fa;
  }

  #trend-post-area {
    margin-top: 80px;
    padding: 12px 24px 12px;
  }

  .post-area {
    width: 70%;
    margin: 80px auto;
  }

  .title-of-this-app {
    text-decoration: none;
    font-size: 36px;
    font-weight: bold;
  }

  .title-of-this-app:hover {
    text-decoration: none;
  }

  #post-btn {
    width: 72%;
    margin: 12px auto;
    border-radius: 20px;
  }

  .signup {
    width: 64%;
    margin: 40px auto;
  }

  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
    padding-top: 120px;
  }

  .login-to-signup {
    text-align: center;
  }

  .form-post {
    width: 76%;
    margin: 0 auto;
  }
  
  .article-title {
    color: #444444;
  }
  
  a.article-title:hover {
    color: #428bca;
    text-decoration: none;
  }
  
  .article-content {
    white-space: pre-line;
  }
  
  .article-img {
    height: 65px;
    width: 65px;
    margin-right: 16px;
  }
  
  .article-metadata {
    padding-bottom: 1px;
    margin-bottom: 4px;
    border-bottom: 1px solid #e3e3e3
  }
  
  .article-metadata a:hover {
    color: #333;
    text-decoration: none;
  }

  .not-posted {
    text-align: center;
    margin-top: 140px;
    font-size: 20px;
  }

  .more-detail {
    color: #444444;
  }

  .likes-and-date {
    font-size: 12px;
  }

  .user-profile-username {
    text-align: center;
    padding-top: 40px;
  }

  .delete-post {
    text-decoration: none;
    color: #444444;
    padding-left: 16px;
  }

  .comment-post {
    text-decoration: none;
    color: #444444;
    padding-left: 16px;
  }

  .comment-header {
    text-align: center;
    margin: 24px auto;
  }

  .sidebar-username {
    text-align: center;
    margin: 12px auto;
    font-size: 20px;
  }

  .trend-header {
    font-weight: bold;
    font-size: 32px;
  }

  .list-group > a {
    font-weight: bold;
    font-size: 20px;
  }

  .navbar-nav {
    font-weight: bold;
    font-size: 20px;
    margin: auto;
  }

  .page-header {
    font-weight: bold;
    text-align: center;
  }

  .search-posts {
    margin: 24px auto;
    text-align: center;
    width: 72%;
  }
  </style>

</head>

<body>


    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"><a href="{{ url_for('app.home') }}" class="title-of-this-app"> Twitter </a></div>
      {% if current_user.is_authenticated %}
        <div class="list-group list-group-flush">
          <h5 class="sidebar-username">{{ current_user.username }}さんようこそ！</h5>
          <a href="{{ url_for('app.user_profile', user_id=current_user.id) }}" class="list-group-item list-group-item-action bg-light">自分の投稿</a>
          <a href="{{ url_for('app.search_posts') }}" class="list-group-item list-group-item-action bg-light">投稿を検索する</a>
          <a href="{{ url_for('app.liked_posts', user_id=current_user.id) }}" class="list-group-item list-group-item-action bg-light">いいねした投稿</a>
          <a href="{{ url_for('app.signup') }}" class="list-group-item list-group-item-action bg-light">アカウントの作成</a>
          <a href="{{ url_for('app.post') }}" class="btn btn-primary btn active" id="post-btn" role="button" aria-pressed="true">投稿</a>
        </div>
      {% else %}
        <div class="list-group list-group-flush">
          <a href="{{ url_for('app.search_posts') }}" class="list-group-item list-group-item-action bg-light">投稿を検索する</a>
          <a href="{{ url_for('app.signup') }}" class="list-group-item list-group-item-action bg-light">アカウントの作成</a>
          <a href="{{ url_for('app.post') }}" class="btn btn-primary btn active" id="post-btn" role="button" aria-pressed="true">投稿</a>
        </div>
      {% endif %}
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <nav class="navbar navbar-expand-lg navbar-light bg-light" id="content-header">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('app.home') }}" >Home</a>
              </li>
              {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('app.logout') }}">ログアウト</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('app.login') }}">ログイン</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      <div class="container-fluid" id="post-content-area">
        <div class="post-area">
          {% block content %}{% endblock content %}
        </div>
      </div>
      <div class="col-md-3" id="trend-area">
        {% block trend %}
        {% endblock trend %}
      </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>

</html>

flaskr/templates/comment.html
{% from '_formhelpers.html' import render_field %}
{% extends 'base.html' %}

{% block content %}
<div class="posting-area">
  <form method="POST" class="form-post">
    <dl>
      {{ form.csrf_token }}
      {{ render_field(form.author, value=current_user.username) }}
      {{ render_field(form.content, class="form-control", placeholder='コメント') }}
      {{ render_field(form.comment_id, value=post_id) }}
      {{ form.submit(class="btn btn-primary") }}
    </dl>
  </form>
</div>
{% endblock content %}

flaskr/templates/home.html
{% extends "base.html" %}

{% block content %}
{% if posts %}
  {% for post in posts.items %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ url_for('app.user_profile', user_id=post.user_id) }}">{{ post.author }}</a></h5>
        <p class="card-text">{{ post.content }}</p>
        <p class="card-text likes-and-date">いいね: {{ post.like_count }}　　　{{ post.date_posted }}</p>
        <a href="{{ url_for('app.post_detail', post_id=post.id) }}" class="more-detail" >もっと見る</a>
      </div>
    </div>
  {% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-primary mb-4" href="{{ url_for('app.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
      <a class="btn btn-outline-primary mb-4" href="{{ url_for('app.home', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}

{% else %}
  <p class="not-posted">投稿がありません</p>
{% endif %}
{% endblock content %}

{% block trend %}
<div class="content-section" id="trend-post-area">
  <h3 class="trend-header" id="trend-header">トレンド</h3>
  <p class='text-muted'>人気な投稿を確認しよう
    <ul class="list-group">
      {% for trend_post in trend_posts %}
        <li class="list-group-item list-group-item-light">
          <p><a href="{{ url_for('app.user_profile', user_id=trend_post.user_id) }}" style="font-weight: bold;">{{ trend_post.author }}</a>  さんの投稿　　いいね: {{ trend_post.like_count }}件</p>
          <a href="{{ url_for('app.post_detail', post_id=trend_post.id) }}">見る</a>
        </li>
      {% endfor %}
    </ul>
  </p>
</div>
{% endblock trend %}

flaskr/templates/liked_posts.html
{% extends "base.html" %}

{% block content %}
<h2 class="page-header">いいねした投稿一覧</h2>
{% if liked_posts %}
  {% for liked_post in liked_posts %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ url_for('app.user_profile', user_id=liked_post.user_id) }}">{{ liked_post.author }}</a></h5>
        <p class="card-text">{{ liked_post.content }}</p>
        <p class="card-text likes-and-date">いいね: {{ liked_post.like_count }}　　　{{ liked_post.date_posted }}</p>
        <a href="{{ url_for('app.post_detail', post_id=liked_post.id) }}" class="more-detail" >もっと見る</a>
      </div>
    </div>
  {% endfor %}

{% else %}
  <p class="not-posted">いいねした投稿はありません</p>
{% endif %}
{% endblock content %}

flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block content %}

<form method='POST' class="form-signin">
  <h2 class="page-header">ログイン</h2>
  <p>投稿、コメント、いいねするにはログインが必要です</p>
  <dl>
    {{ form.csrf_token }}
    {{ render_field(form.email, class="form-control") }}
    {{ render_field(form.password, class="form-control") }}
    {{ form.submit(class="btn btn-lg btn-primary btn-block" ) }}
  </dl>
</form>
<p class="login-to-signup">
  <a href="{{ url_for('app.signup') }}">新規登録はこちら</a>
</p>
{% endblock content %}

flaskr/templates/post.html
{% from '_formhelpers.html' import render_field %}
{% extends 'base.html' %}

{% block content %}
<div class="posting-area">
  <form method="POST" class="form-post">
    <dl>
      {{ form.csrf_token }}
      {{ render_field(form.author, value=current_user.username) }}
      {{ render_field(form.content, class="form-control", placeholder='コンテンツ') }}
      {{ render_field(form.user_id, value=current_user.id) }}
      {{ form.submit(class="btn btn-primary") }}
    </dl>
  </form>
</div>
{% endblock content %}

flaskr/templates/post_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><a href="{{ url_for('app.user_profile', user_id=post.user_id) }}">{{ post.author }}</a></h5>
    <p class="card-text">{{ post.content }}</p>
    {% if current_user.is_authenticated %}
      {% if current_user.has_liked_post(post) %}
      <a href="{{ url_for('app.likes', post_id=post.id, action='unlike') }}" class="btn btn-outline-danger">いいね : {{ post.like_count }}</a>
      {% else %}
      <a href="{{ url_for('app.likes', post_id=post.id, action='like') }}" class="btn btn-outline-danger">いいね : {{ post.like_count }}</a>
      {% endif %}
    {% else %}
      <a href="{{ url_for('app.login') }}" class="btn btn-outline-danger">いいね : {{ post.like_count }}</a>
    {% endif %}
    {% if current_user.username == post.author %}
      <a href="{{ url_for('app.delete_post', post_id=post.id) }}" class="btn btn-outline-secondary">投稿の削除</a>
    {% endif %}
    <a href="{{ url_for('app.comment', post_id=post.id) }}" class="btn btn-outline-secondary">コメント</a>
    <p class="card-text likes-and-date">{{ post.date_posted }}</p>
  </div>
</div>

<h3 class="comment-header">コメント一覧</h3>

{% if comments %}
  {% for comment in comments %}
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><a href="{{ url_for('app.user_profile', user_id=post.user_id) }}">{{ comment.author }}</a></h5>
      <p class="card-text">{{ comment.content }}</p>
      <p class="card-text likes-and-date">{{ comment.date_posted }}</p>
      <a href="{{ url_for('app.comment_delete', post_id=post.id, comment_id=comment.id) }}" class="delete-post" >削除</a>
    </div>
  </div>
  {% endfor %}
{% else %}
コメントはまだありません
{% endif %}
{% endblock content %}

flaskr/templates/search_posts.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block content %}
<div class="search-posts">
  <h2 class="page-header">投稿検索</h2>
  <form class="form my-2 my-lg-0" method="POST">
    {{ csrf_token }}
    {{ render_field(form.posts_contents, class="form-control mr-sm-2", placeholder="コンテンツで検索" ) }}
    {{ form.submit(class="btn btn-outline-success my-2 my-sm-0") }}
  </form>
</div>
<div class="posts-list">
  {% if posts %}
    {% for post in posts %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ url_for('app.user_profile', user_id=post.user_id) }}">{{ post.author }}</a></h5>
        <p class="card-text">{{ post.content }}</p>
        <p class="card-text likes-and-date">いいね: {{ post.like_count }}　　　{{ post.date_posted }}</p>
        <a href="{{ url_for('app.post_detail', post_id=post.id) }}" class="more-detail" >もっと見る</a>
      </div>
    </div>
    {% endfor %}
  {% else %}
  <p>投稿を探しましょう！</p>
  {% endif %}
</div>

{% endblock content %}

flaskr/templates/signup.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block content %}
<div class="signup">
  <form method='POST' class="form-signin">
    <h2 class="page-header">アカウント作成</h2>
    <dl>
      {{ form.csrf_token }}
      {{ render_field(form.username, class="form-control") }}
      {{ render_field(form.email, class="form-control") }}
      {{ render_field(form.password, class="form-control") }}
      {{ render_field(form.confirm_password, class="form-control") }}
      {{ form.submit(class="btn btn-lg btn-primary btn-block" ) }}
    </dl>
  </form>
</div>
{% endblock content %}

flaskr/templates/user_profile.html
{% extends "base.html" %}

{% block content %}
<div class="user-profile-username">
  <h3 class="page-header">{{ user.username }}の投稿一覧</h3>
</div>
<div>
{% if posts %}
  {% for post in posts.items %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><a href="">{{ post.author }}</a></h5>
        <p class="card-text">{{ post.content }}</p>
        <p class="card-text">いいね: {{ post.like_count }}　　　{{ post.date_posted }}</p>
        <a href="{{ url_for('app.post_detail', post_id=post.id) }}" class="more-detail" >もっと見る</a>
      </div>
    </div>
  {% endfor %}
{% else %}
<p class="not-posted">投稿がありません</p>
{% endif %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
  {% if posts.page == page_num %}
    <a class="btn btn-primary mb-4" href="{{ url_for('app.home', page=page_num) }}">{{ page_num }}</a>
  {% else %}
    <a class="btn btn-outline-primary mb-4" href="{{ url_for('app.home', page=page_num) }}">{{ page_num }}</a>
  {% endif %}
{% else %}
  ...
{% endif %}
{% endfor %}
</div>
{% endblock content %}